project:
  output-dir: docs
  type: website

format:
  html:
    theme: 
    - minty
    - styles/bootswatch.scss
    
website:
  title: "Margaret Duffy"
  site-url: "https://www.MargaretDuffy.com"
  navbar:
    raw-html: false
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Publications
        href: research.qmd
        
editor: source